### ISSUE TITLE
Verve.app is damaged and can't be opened

### ISSUE THREAD

**Issue by nicoburns** [ParthJadhav/Verve#16]
I'm getting the following error message "Verve.app is damaged and can't be opened" when I try to run Verve. This is with the aarch64 build on an M1 Pro processor running macOS Ventura (13.0.1).

<img width="265" alt="Screenshot 2022-12-29 at 16 28 20" src="https://user-images.githubusercontent.com/1007307/209981756-0f42232a-967c-4a8e-bdb6-c03400ac7eee.png">

**Comment by ParthJadhav** [comment]
Hey @nicoburns , Can you try running this command `xattr -cr /Applications/verve.app `

**Comment by nicoburns** [comment]
Hmm... Well that removes the error. But attempting to open the application (either by double clicking or running `open /Applications/verve.app`) now does nothing at all.

**Comment by ParthJadhav** [comment]
It might have opened . It's an Menu bar app. Try pressing CMD + SHIFT + G

**Comment by ParthJadhav** [comment]
> Hmm... Well that removes the error. But attempting to open the application (either by double clicking or running `open /Applications/verve.app`) now does nothing at all.

I should probably add some indicator that the app has opened 😄

**Comment by nicoburns** [comment]
> It might have opened . It's an Menu bar app.

Hmm... I don't think it has:

- I don't have a menubar icon
- `Cmd-Shift-G` is not working to open it

I thought `Cmd-Shift-G` was working, but it turns out I was just getting Finder's "go to file" dialog, which also uses that keybinding. You may also want to consider a different default key combination because Finder, Chrome, iTerm2 and Sublime Text all have something mapped to Cmd-Shift-G (although admittedly it's probably something I don't mind being overridden in all cases).

**Comment by ParthJadhav** [comment]
> > It might have opened . It's an Menu bar app.
> 
> Hmm... I don't think it has:
> 
> * I don't have a menubar icon
> * `Cmd-Shift-G` is not working to open it
> 
> I thought `Cmd-Shift-G` was working, but it turns out I was just getting Finder's "go to file" dialog, which also uses that keybinding. You may also want to consider a different default key combination because Finder, Chrome, iTerm2 and Sublime Text all have something mapped to Cmd-Shift-G (although admittedly it's probably something I don't mind being overridden in all cases).

Can you check Activity Monitor for the same? If that doesn't work, Can you try using the Intel Version... It's quite hard for me to test on other machines. I'm using M2 and it's working fine. Also it's working fine for people with Intel Macs. 

It would be great if you could help diagnose this issue so I can fix it 😄

**Comment by nicoburns** [comment]
Nothing in Activity Monitor.

The x86 version is different: it doesn't say the package is broken. It complains it is from an unidentified developer, but that can be bypassed by right click -> open. Unfortunately this gives the same result: no error and no running program either.

If I try to run the binary inside the package directly I get the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorImpl { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), file_position: None } }', src/util.rs:56:85
```

**Comment by ParthJadhav** [comment]
Okay Got it, I'm working on a fix. I hope that fixes it. 

So whats happening is, For Verve to display app icons. It first extracts the icons from each app and then stores it in app data directory.

And for that it looks for info.plist file inside the .app of each app you have. It seems that the file is missing is certain app. I'll change the code so that it doesn't fail in that case.

**Comment by ParthJadhav** [comment]
[verve_x86_64.dmg.zip](https://github.com/ParthJadhav/Verve/files/10320733/verve_x86_64.dmg.zip)

Created a test build. Can you try with this @nicoburns

**Comment by ParthJadhav** [comment]
![Screenshot 2022-12-29 at 10 57 26 PM](https://user-images.githubusercontent.com/42001064/209988160-fc52ad94-3e29-4429-831b-90cc34ad3971.png)

Changes👆

**Comment by nicoburns** [comment]
Yep, that seems to fix things.

Perhaps at some point you should add some kind of global crash handler that will allow users to view and/or report these errors rather than just silently crashing.

**Comment by ParthJadhav** [comment]
Right @nicoburns , Will create an issue regarding the same

**Comment by ParthJadhav** [comment]
Fixed in latest commit + Updated the Release section. Thanks for the help @nicoburns
