### ISSUE TITLE
display full path for file search

### ISSUE THREAD

**Issue by benediktms** [ParthJadhav/Verve#33]
When searching for files the path is not displayed which can get confusing, especially when you have many projects that use a similar pattern when naming files, or when compiled/transpiled files maintain the same file name:

<img width="755" alt="Screenshot 2023-01-10 at 00 46 21" src="https://user-images.githubusercontent.com/48836135/211665208-bd9e04c3-7728-4cf6-94a0-dd6ec11e45b3.png">

It would probably be beneficial to display the file path, and perhaps de-prioritise certain directories, e.g. folders with the name `dist` or `target` etc.

**Comment by ParthJadhav** [comment]
Yep, That makes sense. I'll work on this soon. Thanks for creating this issue.
