### ISSUE TITLE
bug: verve incorrectly delgeates control back to the previous window if the user cancels

### ISSUE THREAD

**Issue by benediktms** [ParthJadhav/Verve#37]
If the uses starts verve and decides to cancel the action (by pressing esc), the previous application is not focused correctly. 

E.g. if you were in a code editor, launch verve, cancel you could not immediatly resume typing, you'd have to alt-tab out, and back into the editor.

**Comment by ParthJadhav** [comment]
Yup, Makes sense. I'll work on it today
